name: Publish NuGet Package # Action名称

# 设置触发器
# 以下示例为master分支，Directory.Build.props文件发生变动后，
# 触发本action
on:
  push:
    branches:
      - main # 监听的分支
    paths: # 监听的文件
      - 'Directory.Build.props'

# 设置运行环境及执行步骤
# 作用见step name
jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x' # 修改为你的.NET版本

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: |
          cd EasyApiClient
          dotnet pack EasyApiClient.csproj  --configuration Release --no-build

      # 需在github库中设置${{ secrets.NUGET_API_KEY }}
      - name: Publish NuGet package
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
